In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, root_mean_squared_error, mean_absolute_error, mean_squared_error

In [6]:
os.chdir('C:/Users/Lenovo/OneDrive/Desktop/Machine Learning/Datasets/Datasets')
pizza = pd.read_csv('pizza.csv')
pizza

Promote  Sales
0        23    554
1        56   1339
2        34    815
3        25    609
4        67   1600
5        82   2000
6        46   1000
7        14    300
8         6    150
9        47   1150
10       52   1200
11       88   2000
12       71   1750
13       78   2000
14       66   1500
15       44   1000
16       68   1600
17       90   2000
18       22    550

In [9]:
x = pizza[['Promote']]
y = pizza['Sales']

In [10]:
lr = LinearRegression()
lr.fit(x,y)

LinearRegression()

In [13]:
lr.intercept_, lr.coef_

(np.float64(5.4858653632529695), array([23.50640302]))

In [15]:
tst = np.array([[24],[56],[89]])
tst.shape

(3, 1)

In [ ]:
# Inferencing: The process of applying built model

tst_pred = lr.predict(tst)
tst_pred

c:\Users\dbda.STUDENTSDC\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([ 569.63953788, 1321.84443457, 2097.55573428])

`train test split`

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=25)

In [26]:
x_train

Promote
3        25
1        56
5        82
11       88
9        47
18       22
16       68
8         6
13       78
2        34
12       71
15       44
4        67

In [28]:
lr = LinearRegression()
lr.fit(x_train, y_train)
lr.intercept_, lr.coef_
y_pred = lr.predict(x_test)
y_pred

array([1251.96902344, 2162.07755859,  341.86048828, 1587.27216797,
       1108.26767578,  557.41250977])

In [30]:
y_test

10    1200
17    2000
7      300
14    1500
6     1000
0      554
Name: Sales, dtype: int64

In [ ]:
r2_score(y_test, y_pred)

In [32]:
y_test.values

array([1200, 2000,  300, 1500, 1000,  554])

In [36]:
for i in range(6):
    print(y_test.iloc[i]-y_pred[i])

-51.96902343750003
-162.07755859374993
-41.860488281250696
-87.27216796874995
-108.26767578125009
-3.4125097656254866


In [37]:
mae = np.mean(np.abs(y_test-y_pred))
mae

np.float64(75.80990397135436)

In [40]:
mean_absolute_error(y_test,y_pred)

75.80990397135436

##### Boston

In [43]:
import os

os.chdir('C:/Users/dbda.STUDENTSDC/Desktop/M.L/Datasets')

In [44]:
boston = pd.read_csv('Boston.csv')

In [46]:
boston.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [47]:
x = boston.drop('medv', axis = 1)
y = boston['medv']

In [48]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=25)
lr = LinearRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)
mean_absolute_error(y_test, y_pred)

3.1175694194800814